version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          command: echo Depoly start... 

      - run:
          name: Depoly Over SSH
          command: ./.circleci/deploy-master.sh

      - run:
          command: echo Depoly finish...
